### ISSUE TITLE
can liblas-config be included in package

### ISSUE THREAD

**Issue by cmbarton** [conda-forge/lastools-feedstock#3]
I'm a member of the open source GRASS GIS dev team, and GRASS has an option to be compiled with liblas support for GRASS lidar processing tools. When liblas is compiled from source, it creates a liblas-config file that goes into the ../bin directory. But this file is not present in the conda build of lastools. 

I maintain the Mac binaries for GRASS, and previously have compiled it with with laslib support.  Recently I switched to building GRASS Mac binaries in the Anaconda environment for a variety of reasons. I was happy to find that there is also a lastools package for Anaconda, including the liblas libraries needed for GRASS. However, GRASS needs to reference the liblas-config file in order to compile with liblas support. 

Is there any chance that liblas-config can be included with future updates to this package? 

Thanks
Michael Barton

**Comment by danclewley** [comment]
This is the feedstock for [LAStools](https://github.com/LAStools/LAStools) and LASlib not [libLAS](https://github.com/libLAS/libLAS) which I believe is the library GRASS can be compiled against. The libLAS website has a page explaining the relationship between the two: https://www.liblas.org/lastools.html. The two libraries provide similar functionality but aren't compatible.

From the libLAS website "As of 2014, libLAS has been almost entirely superceded by Martin Isenburg‘s LASlib library."

More specifically this feedstock builds a fork of LAStools (https://github.com/gillins/LAStools/) which adds CMake build scrips. The standard LAStools doesn't provide a `liblas-config` file, we could add one to the fork this is being build against but I think this would only make things between the two libraries more confusing.

I'm going to mark this as closed but if I am incorrect and it is LASlib you need please reopen for further discussion.

**Comment by cmbarton** [comment]
Thanks for the quick response Dan,

I have indeed seen both the open source libLAS code and the LAStools site. The thing is that the Anaconda package installs liblas.dylib into ../lib as well as command line tools in ../bin with the same names as the tools built with the libLAS code. A couple years ago, a colleague on the GRASS project looked into the (then new) LAStools distribution and thought that it could be a drop in replacement for libLAS code. So I was hoping to try this with the Anaconda build. But we need a liblas-config to do it. I'm copying a couple colleagues on GRASS who also might be able to help with this.

Cheers
Michael

**Comment by danclewley** [comment]
LASlib isn't a drop in replacement for libLAS (different function names for one thing) you'd have to modify the GRASS code if you wanted to use LASlib.

**Comment by cmbarton** [comment]
Indeed. But the anaconda package installs liblas, not laslib. 

Michael

**Comment by gillins** [comment]
Yes the library file is called the same, but the contents are different. In an early version of this recipe i renamed the files to be clear, but that broke other software....

**Comment by cmbarton** [comment]
OK. This is good to know. So the file that is named liblas.dylib in the conda package of lastools is in fact laslib?

Michael

**Comment by gillins** [comment]
Yes. Feel free to talk to the lastools maintainer about this confusing situation...

**Comment by cmbarton** [comment]
Thanks for the clarification.

Michael
